//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LyncFellow.Properties {


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {

        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default {
            get {
                return defaultInstance;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::Microsoft.Lync.Model.ContactAvailability RedOnDndCallBusy {
            get {
                return ((global::Microsoft.Lync.Model.ContactAvailability)(this["RedOnDndCallBusy"]));
            }
            set {
                this["RedOnDndCallBusy"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CallUpgrade {
            get {
                return ((bool)(this["CallUpgrade"]));
            }
            set {
                this["CallUpgrade"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IncomingCall_DoDance {
            get {
                return ((bool)(this["IncomingCall_DoDance"]));
            }
            set {
                this["IncomingCall_DoDance"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IncomingCall_DoFlapWings {
            get {
                return ((bool)(this["IncomingCall_DoFlapWings"]));
            }
            set {
                this["IncomingCall_DoFlapWings"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IncomingCall_DoGlowHeart {
            get {
                return ((bool)(this["IncomingCall_DoGlowHeart"]));
            }
            set {
                this["IncomingCall_DoGlowHeart"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IncomingCall_DoBlinkSingleColor {
            get {
                return ((bool)(this["IncomingCall_DoBlinkSingleColor"]));
            }
            set {
                this["IncomingCall_DoBlinkSingleColor"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IncomingCall_DoBlinkRainbow {
            get {
                return ((bool)(this["IncomingCall_DoBlinkRainbow"]));
            }
            set {
                this["IncomingCall_DoBlinkRainbow"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool NewIMConversation_DoDance {
            get {
                return ((bool)(this["NewIMConversation_DoDance"]));
            }
            set {
                this["NewIMConversation_DoDance"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool NewIMConversation_DoFlapWings {
            get {
                return ((bool)(this["NewIMConversation_DoFlapWings"]));
            }
            set {
                this["NewIMConversation_DoFlapWings"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool NewIMConversation_DoGlowHeart {
            get {
                return ((bool)(this["NewIMConversation_DoGlowHeart"]));
            }
            set {
                this["NewIMConversation_DoGlowHeart"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool NewIMConversation_DoBlinkSingleColor {
            get {
                return ((bool)(this["NewIMConversation_DoBlinkSingleColor"]));
            }
            set {
                this["NewIMConversation_DoBlinkSingleColor"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool NewIMConversation_DoBlinkRainbow {
            get {
                return ((bool)(this["NewIMConversation_DoBlinkRainbow"]));
            }
            set {
                this["NewIMConversation_DoBlinkRainbow"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CITrackerPath {
            get {
                return ((string)(this["CITrackerPath"]));
            }
            set {
                this["CITrackerPath"] = value;
            }
        }
    }
}
